# Naive Bayes Tutorial Part 1: Predicting survival from titanic crash

In [3]:
import pandas as pd
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [5]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [7]:
 #inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [8]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [9]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [10]:
# I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female

In [11]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [12]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [13]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [14]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [16]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [17]:
model.fit(X_train,y_train)

GaussianNB()

In [18]:
model.score(X_test,y_test)

0.7985074626865671

In [19]:
X_test[0:10]

     Pclass        Age     Fare  female
676       3  24.500000   8.0500   False
244       3  30.000000   7.2250   False
409       3  29.699118  25.4667    True
371       3  18.000000   6.4958   False
433       3  17.000000   7.1250   False
616       3  34.000000  14.4000   False
242       2  29.000000  10.5000   False
484       1  25.000000  91.0792   False
769       3  32.000000   8.3625   False
693       3  25.000000   7.2250   False

In [20]:
y_test[0:10]

676    0
244    0
409    0
371    0
433    0
616    0
242    0
484    1
769    0
693    0
Name: Survived, dtype: int64

In [21]:
model.predict(X_test[0:10])

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [22]:
model.predict_proba(X_test[:10])

array([[0.96387727, 0.03612273],
       [0.96591355, 0.03408645],
       [0.45017511, 0.54982489],
       [0.95982789, 0.04017211],
       [0.95940501, 0.04059499],
       [0.96834305, 0.03165695],
       [0.92548579, 0.07451421],
       [0.15504935, 0.84495065],
       [0.96689242, 0.03310758],
       [0.96387135, 0.03612865]])

In [23]:
#Calculate the score using cross validation

In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.824     , 0.72      , 0.76      , 0.77419355, 0.77419355])